<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio de NumPy

In [2]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
lista_array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array_unidimensional_ej1 = np.array(lista_array)
array_unidimensional_ej1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [4]:
print(f"El array original es: \n {array_unidimensional_ej1}\n")
array_unidimensional_modif = np.reshape(array_unidimensional_ej1, (2, 5))
print(f"El array modificado es: \n {array_unidimensional_modif}")

El array original es: 
 [0 1 2 3 4 5 6 7 8 9]

El array modificado es: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [5]:
lista_array_ej2 = [0, 2, 0, 3, 0, 4, 0]

array_unidimensional_ej2 = np.array(lista_array_ej2)
resultado_where = np.where(array_unidimensional_ej2 != 0)
# La función np.where me devuelve los índices de los elementos que cumplen con la condición indicada.
print(f"Mi array inicial es {array_unidimensional_ej2}")
print(f"Los índices de los elementos diferentes de cero del array son {resultado_where}")
#usar lo de la máscara y el true false

Mi array inicial es [0 2 0 3 0 4 0]
Los índices de los elementos diferentes de cero del array son (array([1, 3, 5]),)


#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
#el método random.rand me devuelve la matriz con datos aleatorios entre 0 y 1 directamente.Se podría usar también, random.randint si le indicamos el rango
# de números entre los que queremos que nos genere los elementos de la matriz. 
array_bidimensional_ej4 = np.random.rand(3,3)
array_bidimensional_ej4
# no se puede usar randint pq solo va a devolver números enteros. 

array([[0.94953666, 0.48557568, 0.41439913],
       [0.63914193, 0.75939706, 0.20168688],
       [0.09557474, 0.63146085, 0.73624519]])

#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [7]:
array_unidimensional_ej5 = np.random.randint(1,10, (1,10))

# El método np.arange me crea un array con el máximo de 9 en este caso.

valor_maximo = np.max(array_unidimensional_ej5)
valor_minimo = np.min(array_unidimensional_ej5)

print(array_unidimensional_ej5)
print(valor_maximo)
print(valor_minimo)

[[8 5 4 7 8 9 1 7 7 6]]
9
1


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

La inversa de una matriz cuadrada <i>A</i>, y expresada como <i>A<sup>-1</sup></i>, es aquella matriz que, al multiplicarla por <i>A</i>, da como resultado la matriz identidad del orden correspondiente, .


$$
A \cdot A^{-1} = I = A^{-1} \cdot A
$$

No siempre va a existir la amtriz inversa, ya que se tiene que cumplir que el determinante de la amtriz sea diferente de 0. Esta es condición necesaria y suficiente. 

$$
\exists A^{-1} \iff |A| \neq 0
$$

Para calcular la matriz inversa en python vamos a usar la función np.linalg.inv(matriz). Esta función calcula la inversa de una matriz cuadrada, ya que en caso de que no sea cuadrada, devolverá error. Adjuntamos a continuación el enlace a la documentación correspondiente: https://numpy.org/doc/2.1/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv






In [8]:
array_ej6 = np.random.randint(1, 10, (3,2))
array_ej6

array([[7, 7],
       [5, 1],
       [1, 6]], dtype=int32)

In [9]:
try: 
    determinante_matriz = np.linalg.det(array_ej6)
    inversa_array = np.linalg.inv(array_ej6)
    print(f"La inversa de la matriz es: \n {inversa_array} \n")
    print(f"El determinante de la matriz es: \n {determinante_matriz}")
except np.linalg.LinAlgError: 
    print("La matriz no es cuadrada, por lo que no se puede calcular la inversa ni el determinante")

La matriz no es cuadrada, por lo que no se puede calcular la inversa ni el determinante



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [10]:
array_tridimensional1 = np.random.randint(1, 24, (2,3,4))
print(array_tridimensional1)



[[[12 23 12 20]
  [ 7  9 22 12]
  [16 18 13 20]]

 [[15 22 16 22]
  [ 6 18  5 15]
  [22 17 22  9]]]


In [11]:
primer_quince = array_tridimensional1[0,2,2]
primer_array = array_tridimensional1[0,:]
ultima_fila_array = array_tridimensional1[1,2,:]
print(primer_quince,"\n")
print(primer_array, "\n")
print(ultima_fila_array,"\n")


13 

[[12 23 12 20]
 [ 7  9 22 12]
 [16 18 13 20]] 

[22 17 22  9] 




#### Ejercicio 8 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [12]:
array_tridimensional2 = np.random.randint(1, 30, (3,2,5))
array_tridimensional2

array([[[10, 20,  4, 10, 16],
        [27, 14, 14, 20, 11]],

       [[14, 23, 22, 17,  7],
        [16, 12, 13, 12,  9]],

       [[ 2, 26, 18,  3, 13],
        [24,  4, 26, 17,  2]]], dtype=int32)

In [13]:
dos_prim_elem_fila = array_tridimensional2[0,:,0]
todas_filas_utl_arrays = array_tridimensional2[1:,1:,:]
print(dos_prim_elem_fila, "\n")
print(todas_filas_utl_arrays)

[10 27] 

[[[16 12 13 12  9]]

 [[24  4 26 17  2]]]


#### Ejercicio 9 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [14]:
array_tridimensional_ej9 = np.random.randint(1, 24, (4,3,2))
array_tridimensional_ej9


array([[[ 4,  9],
        [21, 20],
        [14,  7]],

       [[ 6, 20],
        [ 7, 10],
        [19, 12]],

       [[10, 15],
        [17,  5],
        [12, 12]],

       [[20, 18],
        [ 4, 20],
        [ 8, 13]]], dtype=int32)

In [15]:
def modificar_array_ej9(array_ej9):

    array_ej9[1, 1, : ] = 0
    array_ej9[3, : , : ] = -1
    return array_ej9

modificar_array_ej9(array_tridimensional_ej9)

array([[[ 4,  9],
        [21, 20],
        [14,  7]],

       [[ 6, 20],
        [ 0,  0],
        [19, 12]],

       [[10, 15],
        [17,  5],
        [12, 12]],

       [[-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int32)


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [16]:
array_tridimensional_ej10 = np.random.randint(-10, 13, (2,4,3))
array_tridimensional_ej10

array([[[ 5, -4,  6],
        [-6, -4,  2],
        [ 0, -7,  9],
        [-8, -8,  2]],

       [[-7, -1,  7],
        [-9, 10,  4],
        [ 1,  1,  9],
        [ 3, -3, -5]]], dtype=int32)

In [17]:
def modificar_array_ej10(array_ej10):

    print(f"Los elementos de mayores a 5 del array tridimensional son: {array_ej10[array_ej10 > 5]}")  
    array_ej10[array_ej10 < 0] = 0
    return array_ej10

modificar_array_ej10(array_tridimensional_ej10)

Los elementos de mayores a 5 del array tridimensional son: [ 6  9  7 10  9]


array([[[ 5,  0,  6],
        [ 0,  0,  2],
        [ 0,  0,  9],
        [ 0,  0,  2]],

       [[ 0,  0,  7],
        [ 0, 10,  4],
        [ 1,  1,  9],
        [ 3,  0,  0]]], dtype=int32)

#### Ejercicio 11 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [18]:
array_tridimensional_ej11 = np.random.randint(1, 27, (3,3,3))
array_tridimensional_ej11

array([[[12,  3, 21],
        [ 3,  8, 24],
        [14, 10, 25]],

       [[12, 17, 13],
        [21,  4,  9],
        [21, 16, 17]],

       [[ 2,  2,  2],
        [20, 16, 11],
        [15, 24,  5]]], dtype=int32)

In [19]:
def seleccionar_elem_ej11(array_ej11):
    
    print(f"{array_ej11[1, : , : 2]}")
    valores_mayores20 = array_ej11[array_ej11 > 20]
    return valores_mayores20

seleccionar_elem_ej11(array_tridimensional_ej11)

[[12 17]
 [21  4]
 [21 16]]


array([21, 24, 25, 21, 21, 24], dtype=int32)

#### Ejercicio 12 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

TERMINAR

In [20]:
array_ejercicio12 = np.round(np.random.rand(10), 3)
array_ejercicio12

array([0.034, 0.95 , 0.821, 0.459, 0.39 , 0.192, 0.139, 0.002, 0.147,
       0.329])

In [21]:
valor_maximo = np.max(array_ejercicio12)
valor_minimo = np.min(array_ejercicio12)
print(f"El valor máximo del array es {valor_maximo}")
print(f"El valor máximo del array es {valor_minimo}")

array_ejercicio12[array_ejercicio12 == valor_maximo] = 0
array_ejercicio12[array_ejercicio12 == valor_minimo] = 0
array_ejercicio12


El valor máximo del array es 0.95
El valor máximo del array es 0.002


array([0.034, 0.   , 0.821, 0.459, 0.39 , 0.192, 0.139, 0.   , 0.147,
       0.329])

#### Ejercicio 13 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [22]:
array_ejercicio13 = np.random.randint(1,100, 15)
array_ejercicio13

array([99, 20, 78, 13,  9,  1, 21, 96, 17, 23, 11, 16, 73, 60, 32],
      dtype=int32)

In [23]:
array_ordenado = np.sort(array_ejercicio13)
array_ordenado

array([ 1,  9, 11, 13, 16, 17, 20, 21, 23, 32, 60, 73, 78, 96, 99],
      dtype=int32)

#### Ejercicio 14 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [24]:
array_ejercicio14 = np.random.randint(1, 10, (4,4))
array_ejercicio14

array([[6, 7, 3, 2],
       [1, 9, 7, 6],
       [9, 5, 3, 5],
       [8, 5, 3, 4]], dtype=int32)

**Realización mediante uso de fórmula**

La función np.add.reduce permite realizar la suma de los elementos de un array por ejes. Me devolverá una lista con los elementos correspondientes a la suma de cada eje. En este caso, al ser una matriz cuadrada me devolverá una lista con 4 elementos tanto para filas como para columnas

In [25]:
b_filas = np.add.reduce(array_ejercicio14, axis=1)
b_columnas = np.add.reduce(array_ejercicio14, axis=0)
print(f"La suma de los elementos de las filas es: {b_filas}")
print(f"La suma de los elementos de las columnas es:{b_columnas}") 



La suma de los elementos de las filas es: [18 23 22 20]
La suma de los elementos de las columnas es:[24 26 16 17]


**Forma manual de realizarlo**


In [26]:
suma_fila1 = np.sum(array_ejercicio14[0, : ])
suma_fila2 = np.sum(array_ejercicio14[1, : ])
suma_fila3 = np.sum(array_ejercicio14[2, : ])
suma_fila4 = np.sum(array_ejercicio14[3, : ])
suma_columna1 = np.sum(array_ejercicio14[:, 0])
suma_columna2 = np.sum(array_ejercicio14[:, 1])
suma_columna3 = np.sum(array_ejercicio14[:, 2])
suma_columna4 = np.sum(array_ejercicio14[:, 3])

In [27]:
print(f"{suma_fila1}")
print(f"{suma_fila2}")
print(f"{suma_fila3}")
print(f"{suma_fila4}")
print(f"{suma_columna1}")
print(f"{suma_columna2}")
print(f"{suma_columna3}")
print(f"{suma_columna4}")

18
23
22
20
24
26
16
17


#### Ejercicio 15 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

**Uso de la función eye()**

La función eye nos permite crear una matriz diagnoal de identidad de nxn. Para ello se debe pasar la dimensión de la matriz en el argumento a pasar.

Cuidado: solo genera matrices cuadradas, por lo que si le pasamos un 4, será una 4x4, pero no podrá crear por ejemplo una 3x4.

In [28]:
array_ejericio15 = np.eye(5)
array_ejericio15



array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
lista_diag = [1, 1, 1, 1, 1]
array_ejericio15_1 = np.diag(lista_diag)
array_ejericio15_1



array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

#### Ejercicio 16 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [30]:
array_ejercicio16 = np.random.random(10)
array_ejercicio16

array([0.15581437, 0.00652589, 0.27673467, 0.9728962 , 0.46694069,
       0.45986785, 0.71974118, 0.39873068, 0.61059029, 0.25545141])

In [31]:
media_array_ej16 = round(np.mean(array_ejercicio16),3)
desviacion_array_ej16 = round(np.std(array_ejercicio16), 3)
print(media_array_ej16)
print(desviacion_array_ej16)

0.432
0.269


#### Ejercicio 17 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [32]:
array_ejercicio17 = np.random.randint(1,24, (2,3,4))
array_ejercicio17

array([[[13, 21,  4,  9],
        [20, 20,  3, 16],
        [ 6,  7, 21, 11]],

       [[ 1, 21, 22,  8],
        [ 7, 22, 22, 17],
        [19, 20, 15,  1]]], dtype=int32)

**Explicación**

Cuando se realiza la transpuesta de una matriz de dimensión mxn, se intercambian las filas por las columnas. Es decir, sea i el elemento de la fila, y j el de la columna, se definirá la transpuesta de la siguiente manera: 
$$
 A^{T}(j,i) = A(i,j)
$$

Cuando realizamos la transpuesta, al final intercambiamos la dimensión de la matriz original. En el ejercicio empezamos teniendo un array de dos tridimensional, es decir, compuesto de dos matrices, que contienen tres filas y cuatro columnas cada una. AL realizar la transpuesta nos quedará un array tridimensional, con cuatro matrices, las cuales van a contener tres filas y dos columnas cada una.


In [33]:
transpuesta_array_ej17 = np.transpose(array_ejercicio17)
print(f"{transpuesta_array_ej17.shape}") 
transpuesta_array_ej17

(4, 3, 2)


array([[[13,  1],
        [20,  7],
        [ 6, 19]],

       [[21, 21],
        [20, 22],
        [ 7, 20]],

       [[ 4, 22],
        [ 3, 22],
        [21, 15]],

       [[ 9,  8],
        [16, 17],
        [11,  1]]], dtype=int32)

#### Ejercicio 18 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [34]:
array_ejercicio18 = np.random.randint(1,24, (3,4,2))
array_ejercicio18

array([[[19, 11],
        [ 6,  2],
        [20, 18],
        [11, 20]],

       [[22, 15],
        [ 9,  6],
        [17, 13],
        [ 4,  4]],

       [[22,  8],
        [15, 15],
        [17, 21],
        [16, 13]]], dtype=int32)

In [35]:
array_modificado_ej18 = np.transpose(array_ejercicio18, (1, 0, 2))
print(f"{array_modificado_ej18.shape}") 
array_modificado_ej18

(4, 3, 2)


array([[[19, 11],
        [22, 15],
        [22,  8]],

       [[ 6,  2],
        [ 9,  6],
        [15, 15]],

       [[20, 18],
        [17, 13],
        [17, 21]],

       [[11, 20],
        [ 4,  4],
        [16, 13]]], dtype=int32)

#### Ejercicio 19 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [36]:
array_ejercicio19 = np.random.randint(1,24, (3,2,4))
array_ejercicio19

array([[[21,  6,  1,  1],
        [22,  4,  7, 20]],

       [[ 6, 23,  1, 13],
        [19, 16, 12,  7]],

       [[19, 15, 11, 11],
        [ 6, 14, 18, 11]]], dtype=int32)

In [37]:
array_modificado_ej19 = np.transpose(array_ejercicio19, (2, 0, 1))
print(f"{array_modificado_ej19.shape}") 
array_modificado_ej19

(4, 3, 2)


array([[[21, 22],
        [ 6, 19],
        [19,  6]],

       [[ 6,  4],
        [23, 16],
        [15, 14]],

       [[ 1,  7],
        [ 1, 12],
        [11, 18]],

       [[ 1, 20],
        [13,  7],
        [11, 11]]], dtype=int32)

#### Ejercicio 20 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [38]:
array_ejercicio20 = np.random.randint(-10, 10,(3,4,5))
array_ejercicio20

array([[[  8,  -2,  -3,  -7,   2],
        [  6, -10,   2,  -1,   2],
        [  9,   2,  -9,  -7,  -3],
        [ -2,   1,   0,   3,  -4]],

       [[ -6,   2,   2,  -3,  -5],
        [  5,   9,  -9,  -1,   2],
        [  9,  -9,  -2,   7,   9],
        [  4,  -7,  -4,  -1,   4]],

       [[ -4,  -2,   7,   0,   7],
        [  0,  -3,  -9,  -1,   8],
        [ -2,   1,  -2,   0,   1],
        [  6,  -7, -10,   4,   4]]], dtype=int32)

In [39]:
array_vacio = np.empty((3,4,5), dtype = str)
array_vacio

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [69]:
mediana_array_ej20 = np.median(array_ejercicio20)
print(f"La mediana del array tiene un valor de {mediana_array_ej20}")
maximo_array_ej20 = np.max(array_ejercicio20)
print(f"El valor maximo del array es {maximo_array_ej20}")
minimo_array_ej20 = np.min(array_ejercicio20)
print(f"El valor minimo del array es {minimo_array_ej20} \n")



array_vacio[array_vacio == str(maximo_array_ej20) ] = "MAX"

array_vacio[array_vacio == str(minimo_array_ej20)] = "MIN"
array_vacio[array_vacio == mediana_array_ej20] = "M"

array_vacio[array_vacio < str(mediana_array_ej20)] = "Y"

array_vacio[array_vacio > str(mediana_array_ej20)] = "X"


print(array_vacio)

La mediana del array tiene un valor de 0.0
El valor maximo del array es 9
El valor minimo del array es -10 

[[['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']]

 [['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']]

 [['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']
  ['X' 'X' 'X' 'X' 'X']]]


#### Ejercicio 21 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [51]:
array_ejercicio21 = np.random.rand(2,4,4)
print(f"La matriz original es: \n {array_ejercicio21}  \n")

matriz_original_copia = array_ejercicio21.copy()
print(f"La copia de la original es: \n {matriz_original_copia} \n")

La matriz original es: 
 [[[0.80600627 0.26234802 0.72216037 0.68954768]
  [0.55497238 0.63788278 0.32455478 0.50312433]
  [0.60376009 0.90383514 0.78052346 0.68387241]
  [0.814923   0.032478   0.06504284 0.60992788]]

 [[0.36887818 0.68370972 0.26431947 0.7235497 ]
  [0.23071194 0.82990911 0.16147442 0.2395092 ]
  [0.88844555 0.28274758 0.81116809 0.14766096]
  [0.00879683 0.7204451  0.40067287 0.11765591]]]  

La copia de la original es: 
 [[[0.80600627 0.26234802 0.72216037 0.68954768]
  [0.55497238 0.63788278 0.32455478 0.50312433]
  [0.60376009 0.90383514 0.78052346 0.68387241]
  [0.814923   0.032478   0.06504284 0.60992788]]

 [[0.36887818 0.68370972 0.26431947 0.7235497 ]
  [0.23071194 0.82990911 0.16147442 0.2395092 ]
  [0.88844555 0.28274758 0.81116809 0.14766096]
  [0.00879683 0.7204451  0.40067287 0.11765591]]] 



In [81]:
fila = 0
columna = 0
matriz = 0

lista_filas = []
for elemento in array_ejercicio21[matriz,fila]:
    lista_filas.append(elemento)

print(lista_filas)

lista_columnas = []
for elemento in matriz_original_copia[matriz, :, columna]:
    lista_columnas.append(elemento)

print(lista_columnas)


while len(lista_filas) == len(lista_columnas):
    
    if lista_filas == lista_columnas:
        print("tenemos igualdad")
    fila += 1
    columna += 1
    matriz += 1


    

[np.float64(0.8060062717108086), np.float64(0.2623480222650433), np.float64(0.7221603726021631), np.float64(0.6895476814204972)]
[np.float64(1.8060062717108085), np.float64(1.5549723832850604), np.float64(1.6037600882190914), np.float64(1.8149229961048192)]


KeyboardInterrupt: 